  version: "3.9"

  services:

    back_app:
      container_name: java_app
      image: pee-java-app:1.0.0
      build: .
      ports:
        - "8080:8080"
      environment:
        DB_URL: jdbc:mysql://short_db:3306/short?createDatabaseIfNotExist=TRUE&serverTimezone=UTC
        DB_USER: root
        DB_PASS: root
        WEB_URL: localhost
        WEB_PORT: 8080
      restart: always
      depends_on:
        short_db:
          condition: service_healthy
    short_db:
      container_name: java_db
      image: mysql:8.0.33
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: short
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 5s
        timeout: 10s
        retries: 10